const prom = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject("PoraÅ¼ka")
    }, 2000);
    
})
prom.then(res => console.log(res))  
    .catch(err => console.log(err))